"""add twitch_client_secret

Revision ID: 534f3c177740
Revises: 5958d29477ff
Create Date: 2026-09-03 08:59:46.259757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534f3c177740'
down_revision = '5958d29477ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitch_client_secret', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('twitch_client_secret')

    # ### end Alembic commands ###
