"""initial schema

Revision ID: 5958d29477ff
Revises: 
Create Date: 2026-09-03 08:17:02.440979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5958d29477ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streamers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('username_lower', sa.String(), nullable=False),
    sa.Column('broadcaster_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('streamers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streamers_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_streamers_username_lower'), ['username_lower'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('twitch_client_id', sa.String(), nullable=True),
    sa.Column('twitch_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('streamers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streamers_username_lower'))
        batch_op.drop_index(batch_op.f('ix_streamers_username'))

    op.drop_table('streamers')
    # ### end Alembic commands ###
